# Generated by Django 6.0.7 on 2026-07-09 20:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0002_familymember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(choices=[('ONCE_DAILY', 'Once'), ('TWICE_DAILY', 'Twice'), ('THRICE_DAILY', 'Thrice'), ('WEEKLY', 'Weekly'), ('AS_NEEDED', 'As Needed')], max_length=30)),
                ('times', models.JSONField(default=list)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('instructions', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='families.familymember')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('TAKEN', 'Taken'), ('MISSED', 'Missed')], default='PENDING', max_length=20)),
                ('marked_at', models.DateTimeField(blank=True, null=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicines.medicine')),
            ],
            options={
                'unique_together': {('medicine', 'scheduled_date', 'scheduled_time')},
            },
        ),
    ]
