# Generated by Django 6.0.7 on 2026-07-09 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0003_remove_familymember_created_by_and_more'),
        ('habits', '0002_alter_habitlog_family_member'),
        ('medicines', '0002_alter_medicine_family_member'),
        ('reports', '0002_alter_medicalreport_family_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FamilyMember',
        ),
        migrations.AlterUniqueTogether(
            name='familymembership',
            unique_together={('family', 'user')},
        ),
    ]
