# Generated by Django 6.0.7 on 2026-07-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0004_delete_familymember_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymembership',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('CAREGIVER', 'Caregiver'), ('MEMBER', 'Member')], max_length=20),
        ),
    ]
