# Generated by Django 6.0.7 on 2026-07-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='blood_group',
            field=models.TextField(blank=True, null=True),
        ),
    ]
