# Generated by Django 6.0.7 on 2026-07-09 20:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0002_familymember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_url', models.URLField()),
                ('file_type', models.CharField(choices=[('PDF', 'Pdf'), ('IMAGE', 'Image')], max_length=10)),
                ('original_filename', models.CharField(max_length=255)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('ocr_text', models.TextField(blank=True, null=True)),
                ('ocr_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('ai_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='families.familymember')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AISummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField()),
                ('key_findings', models.JSONField(default=list)),
                ('abnormal_values', models.JSONField(default=list)),
                ('model_version', models.CharField(max_length=100)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reports.medicalreport')),
            ],
        ),
    ]
