# Generated by Django 6.0.7 on 2026-07-09 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreport',
            name='family_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.familymember'),
        ),
    ]
