# Generated by Django 6.0.7 on 2026-07-11 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_medicalreport_family_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalreport',
            name='file_url',
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='file_path',
            field=models.CharField(default='reports/placeholder.pdf', max_length=500),
            preserve_default=False,
        ),
    ]
