# Generated by Django 6.0.7 on 2026-07-11 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_familymember_linked_user'),
        ('reports', '0003_remove_medicalreport_file_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalreport',
            name='ocr_text',
        ),
        migrations.AddField(
            model_name='aisummary',
            name='recommendations',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='aisummary',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_summary', to='reports.medicalreport'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='family_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_reports', to='members.familymember'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_text', models.TextField()),
                ('engine', models.CharField(default='Gemini OCR', max_length=100)),
                ('processed_at', models.DateTimeField(auto_now=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_result', to='reports.medicalreport')),
            ],
        ),
    ]
