# Generated by Django 6.0.7 on 2026-07-12 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_medicalreport_ocr_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisummary',
            name='structured_report',
            field=models.JSONField(default=dict),
        ),
    ]
