# Generated by Django 6.0.7 on 2026-07-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_aisummary_structured_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisummary',
            name='model_version',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
