# Generated by Django 6.0.7 on 2026-07-12 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_aisummary_model_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('reference_range', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='reports.medicalreport')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
