# Generated by Django 6.0.7 on 2026-07-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_reporttest'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttest',
            name='normalized_name',
            field=models.CharField(db_index=True, default='uknown', max_length=100),
            preserve_default=False,
        ),
    ]
