# Generated by Django 6.0.7 on 2026-07-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_reporttest_normalized_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='report_type',
            field=models.CharField(blank=True, db_index=True, default='Other', max_length=50),
        ),
    ]
