# Generated by Django 6.0.7 on 2026-07-09 20:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0004_delete_familymember_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDigest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('digest_date', models.DateField()),
                ('content', models.JSONField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='families.family')),
            ],
            options={
                'unique_together': {('family', 'digest_date')},
            },
        ),
    ]
